In [6]:
import numpy as np

In [10]:
a = np.asarray([1,2,3],dtype='float32')

In [11]:
print(type(a))

<class 'numpy.ndarray'>


In [12]:
print(a)

[1. 2. 3.]


In [13]:
print(a.shape)

(3,)


In [40]:
b = np.array([[1,2,0],[3,4,0],[3,8,0]])
print(b)

[[1 2 0]
 [3 4 0]
 [3 8 0]]


In [41]:
print(b.shape)

(3, 3)


In [43]:
b[1:,1:] = 100
print(b)

[[  1   2   0]
 [  3 100 100]
 [  3 100 100]]


In [50]:
six_identity = 6*np.eye(5,dtype='int32')
print(six_identity)

[[6 0 0 0 0]
 [0 6 0 0 0]
 [0 0 6 0 0]
 [0 0 0 6 0]
 [0 0 0 0 6]]


In [52]:
np.random.randint(10,20,(5,5))

array([[15, 18, 19, 17, 19],
       [11, 18, 16, 18, 12],
       [10, 16, 18, 12, 11],
       [14, 18, 19, 10, 13],
       [18, 17, 19, 15, 12]])

In [65]:
a2 = np.random.randint(10,20,(5,))

In [66]:
a1 = np.random.randint(0,10,(5,1))

In [67]:
print(a1)

[[5]
 [7]
 [8]
 [1]
 [8]]


In [75]:
print(a2)
print(np.max(a2))
print(np.min(a2))
print(np.sum(a2))
print(np.mean(a2))


[18 13 14 10 15]
18
10
70
14.0


In [76]:
np.exp?

In [63]:
a3 = np.random.randint(10,20,(5,5,6)) #Tensor

In [77]:
a = np.random.randint(1,5,(3,4))
print(a)

[[3 2 3 2]
 [4 2 1 4]
 [2 4 3 4]]


In [79]:
b = a+5

In [81]:
c = b - a
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [86]:
l = np.array([1,2,3,5])
print(l+c)

[[ 6  7  8 10]
 [ 6  7  8 10]
 [ 6  7  8 10]]


In [83]:
l


array([1, 2, 3, 4])

In [87]:
l**2

array([ 1,  4,  9, 25], dtype=int32)

In [93]:
print(a)

[[10  2  3  2]
 [ 4  2  1  4]
 [ 2  4  3  4]]


In [108]:
b = np.array(a) #create a copy of a 

In [109]:
b[0][0] = 20

In [110]:
print(b)

[[20  2  3  2]
 [ 4  2  1  4]
 [ 2  4  3  4]]


In [111]:
print(a)

[[10  2  3  2]
 [ 4  2  1  4]
 [ 2  4  3  4]]


In [112]:
c = np.vstack((a,b))

In [113]:
print(c)

[[10  2  3  2]
 [ 4  2  1  4]
 [ 2  4  3  4]
 [20  2  3  2]
 [ 4  2  1  4]
 [ 2  4  3  4]]


In [114]:
d = np.hstack((a,b))

In [115]:
print(d)

[[10  2  3  2 20  2  3  2]
 [ 4  2  1  4  4  2  1  4]
 [ 2  4  3  4  2  4  3  4]]
